// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class ActorInfo
{
    public ushort ActorId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FilmInfo { get; set; }
}