<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class ActorInfo
{
    public ushort ActorId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FilmInfo { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class ActorInfo
    {
        public ushort ActorId { get; set; }
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? FilmInfo { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
