// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakila.Domain;

[Keyless]
public partial class ActorInfo
{
    [Column("actor_id")]
    public ushort ActorId { get; set; }

    [Required]
    [Column("first_name")]
    [StringLength(45)]
    public string FirstName { get; set; }

    [Required]
    [Column("last_name")]
    [StringLength(45)]
    public string LastName { get; set; }

    [Column("film_info", TypeName = "text")]
    public string FilmInfo { get; set; }
}