// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakila.Domain;

[Table("address")]
[Index("CityId", Name = "idx_fk_city_id")]
public partial class Address
{
    [Key]
    [Column("address_id")]
    public ushort AddressId { get; set; }

    [Required]
    [Column("address")]
    [StringLength(50)]
    public string Address1 { get; set; }

    [Column("address2")]
    [StringLength(50)]
    public string Address2 { get; set; }

    [Required]
    [Column("district")]
    [StringLength(20)]
    public string District { get; set; }

    [Column("city_id")]
    public ushort CityId { get; set; }

    [Column("postal_code")]
    [StringLength(10)]
    public string PostalCode { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(20)]
    public string Phone { get; set; }

    [Column("last_update", TypeName = "timestamp")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Address")]
    public virtual City City { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    [InverseProperty("Address")]
    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();

    [InverseProperty("Address")]
    public virtual ICollection<Store> Store { get; set; } = new List<Store>();
}