// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakila.Domain;

[Table("city")]
[Index("CountryId", Name = "idx_fk_country_id")]
public partial class City
{
    [Key]
    [Column("city_id")]
    public ushort CityId { get; set; }

    [Required]
    [Column("city")]
    [StringLength(50)]
    public string CityName { get; set; }

    [Column("country_id")]
    public ushort CountryId { get; set; }

    [Column("last_update", TypeName = "timestamp")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Address> Address { get; set; } = new List<Address>();

    [ForeignKey("CountryId")]
    [InverseProperty("City")]
    public virtual Country Country { get; set; }
}