// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Country
{
    public ushort CountryId { get; set; }

    public string Country1 { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual ICollection<City> City { get; set; } = new List<City>();
}