<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Customer
{
    public ushort CustomerId { get; set; }

    public byte StoreId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public ushort AddressId { get; set; }

    public bool? Active { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? LastUpdate { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<Payment> Payment { get; set; } = new List<Payment>();

    public virtual ICollection<Rental> Rental { get; set; } = new List<Rental>();

    public virtual Store Store { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class Customer
    {
        public Customer()
        {
            Payments = new HashSet<Payment>();
            Rentals = new HashSet<Rental>();
        }

        public ushort CustomerId { get; set; }
        public byte StoreId { get; set; }
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? Email { get; set; }
        public ushort AddressId { get; set; }
        public bool? Active { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Address Address { get; set; } = null!;
        public virtual Store Store { get; set; } = null!;
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
