<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class CustomerList
{
    public ushort Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string ZipCode { get; set; }

    public string Phone { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string Notes { get; set; }

    public byte Sid { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class CustomerList
    {
        public ushort Id { get; set; }
        public string? Name { get; set; }
        public string Address { get; set; } = null!;
        public string? ZipCode { get; set; }
        public string Phone { get; set; } = null!;
        public string City { get; set; } = null!;
        public string Country { get; set; } = null!;
        public string Notes { get; set; } = null!;
        public byte Sid { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
