<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Film
{
    public ushort FilmId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public short? ReleaseYear { get; set; }

    public byte LanguageId { get; set; }

    public byte? OriginalLanguageId { get; set; }

    public byte RentalDuration { get; set; }

    public decimal RentalRate { get; set; }

    public ushort? Length { get; set; }

    public decimal ReplacementCost { get; set; }

    public string Rating { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual ICollection<FilmActor> FilmActor { get; set; } = new List<FilmActor>();

    public virtual ICollection<FilmCategory> FilmCategory { get; set; } = new List<FilmCategory>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual Language Language { get; set; }

    public virtual Language OriginalLanguage { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class Film
    {
        public Film()
        {
            FilmActors = new HashSet<FilmActor>();
            FilmCategories = new HashSet<FilmCategory>();
            Inventories = new HashSet<Inventory>();
        }

        public ushort FilmId { get; set; }
        public string Title { get; set; } = null!;
        public string? Description { get; set; }
        public short? ReleaseYear { get; set; }
        public byte LanguageId { get; set; }
        public byte? OriginalLanguageId { get; set; }
        public byte RentalDuration { get; set; }
        public decimal RentalRate { get; set; }
        public ushort? Length { get; set; }
        public decimal ReplacementCost { get; set; }
        public string? Rating { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Language Language { get; set; } = null!;
        public virtual Language? OriginalLanguage { get; set; }
        public virtual ICollection<FilmActor> FilmActors { get; set; }
        public virtual ICollection<FilmCategory> FilmCategories { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
