<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class FilmCategory
{
    public ushort FilmId { get; set; }

    public byte CategoryId { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual Category Category { get; set; }

    public virtual Film Film { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class FilmCategory
    {
        public ushort FilmId { get; set; }
        public byte CategoryId { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Category Category { get; set; } = null!;
        public virtual Film Film { get; set; } = null!;
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
