// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakila.Domain;

[PrimaryKey("ActorId", "FilmId")]
[Table("film_actor")]
[Index("FilmId", Name = "idx_fk_film_id")]
public partial class FilmActor
{
    [Key]
    [Column("actor_id")]
    public ushort ActorId { get; set; }

    [Key]
    [Column("film_id")]
    public ushort FilmId { get; set; }

    [Column("last_update", TypeName = "timestamp")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("ActorId")]
    [InverseProperty("FilmActor")]
    public virtual Actor Actor { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("FilmActor")]
    public virtual Film Film { get; set; }
}