// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Film
{
    public ushort FilmId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public short? ReleaseYear { get; set; }

    public byte LanguageId { get; set; }

    public byte? OriginalLanguageId { get; set; }

    public byte RentalDuration { get; set; }

    public decimal RentalRate { get; set; }

    public ushort? Length { get; set; }

    public decimal ReplacementCost { get; set; }

    public string Rating { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual ICollection<FilmActor> FilmActor { get; set; } = new List<FilmActor>();

    public virtual ICollection<FilmCategory> FilmCategory { get; set; } = new List<FilmCategory>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual Language Language { get; set; }

    public virtual Language OriginalLanguage { get; set; }
}