// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Inventory
{
    public uint InventoryId { get; set; }

    public ushort FilmId { get; set; }

    public byte StoreId { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual Film Film { get; set; }

    public virtual ICollection<Rental> Rental { get; set; } = new List<Rental>();

    public virtual Store Store { get; set; }
}