// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakila.Domain;

[Table("inventory")]
[Index("FilmId", Name = "idx_fk_film_id")]
[Index("StoreId", "FilmId", Name = "idx_store_id_film_id")]
public partial class Inventory
{
    [Key]
    [Column("inventory_id", TypeName = "mediumint unsigned")]
    public uint InventoryId { get; set; }

    [Column("film_id")]
    public ushort FilmId { get; set; }

    [Column("store_id")]
    public byte StoreId { get; set; }

    [Column("last_update", TypeName = "timestamp")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("FilmId")]
    [InverseProperty("Inventory")]
    public virtual Film Film { get; set; }

    [InverseProperty("Inventory")]
    public virtual ICollection<Rental> Rental { get; set; } = new List<Rental>();

    [ForeignKey("StoreId")]
    [InverseProperty("Inventory")]
    public virtual Store Store { get; set; }
}