// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Language
{
    public byte LanguageId { get; set; }

    public string Name { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual ICollection<Film> FilmLanguage { get; set; } = new List<Film>();

    public virtual ICollection<Film> FilmOriginalLanguage { get; set; } = new List<Film>();
}