<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class NicerButSlowerFilmList
{
    public ushort? Fid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public decimal? Price { get; set; }

    public ushort? Length { get; set; }

    public string Rating { get; set; }

    public string Actors { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class NicerButSlowerFilmList
    {
        public ushort? Fid { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string Category { get; set; } = null!;
        public decimal? Price { get; set; }
        public ushort? Length { get; set; }
        public string? Rating { get; set; }
        public string? Actors { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
