<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Rental
{
    public int RentalId { get; set; }

    public DateTime RentalDate { get; set; }

    public uint InventoryId { get; set; }

    public ushort CustomerId { get; set; }

    public DateTime? ReturnDate { get; set; }

    public byte StaffId { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<Payment> Payment { get; set; } = new List<Payment>();

    public virtual Staff Staff { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class Rental
    {
        public Rental()
        {
            Payments = new HashSet<Payment>();
        }

        public int RentalId { get; set; }
        public DateTime RentalDate { get; set; }
        public uint InventoryId { get; set; }
        public ushort CustomerId { get; set; }
        public DateTime? ReturnDate { get; set; }
        public byte StaffId { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Customer Customer { get; set; } = null!;
        public virtual Inventory Inventory { get; set; } = null!;
        public virtual staff Staff { get; set; } = null!;
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
