// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class SalesByFilmCategory
{
    public string Category { get; set; }

    public decimal? TotalSales { get; set; }
}