// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sakila.Domain;

[Keyless]
public partial class SalesByFilmCategory
{
    [Required]
    [Column("category")]
    [StringLength(25)]
    public string Category { get; set; }

    [Column("total_sales")]
    [Precision(27, 2)]
    public decimal? TotalSales { get; set; }
}