<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class SalesByStore
{
    public string Store { get; set; }

    public string Manager { get; set; }

    public decimal? TotalSales { get; set; }
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class SalesByStore
    {
        public string? Store { get; set; }
        public string? Manager { get; set; }
        public decimal? TotalSales { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
