// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Staff
{
    public byte StaffId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public ushort AddressId { get; set; }

    public byte[] Picture { get; set; }

    public string Email { get; set; }

    public byte StoreId { get; set; }

    public bool? Active { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<Payment> Payment { get; set; } = new List<Payment>();

    public virtual ICollection<Rental> Rental { get; set; } = new List<Rental>();

    public virtual Store Store { get; set; }

    public virtual Store StoreNavigation { get; set; }
}