<<<<<<< HEAD
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Store
{
    public byte StoreId { get; set; }

    public byte ManagerStaffId { get; set; }

    public ushort AddressId { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual Staff ManagerStaff { get; set; }

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}
=======
﻿using System;
using System.Collections.Generic;

namespace Sakila.Domain
{
    public partial class Store
    {
        public Store()
        {
            Customers = new HashSet<Customer>();
            Inventories = new HashSet<Inventory>();
            staff = new HashSet<staff>();
        }

        public byte StoreId { get; set; }
        public byte ManagerStaffId { get; set; }
        public ushort AddressId { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Address Address { get; set; } = null!;
        public virtual staff ManagerStaff { get; set; } = null!;
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<staff> staff { get; set; }
    }
}
>>>>>>> 3d945b1de4a8534d7f920ba8042ea88050f35e7e
