// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sakila.Domain;

public partial class Store
{
    public byte StoreId { get; set; }

    public byte ManagerStaffId { get; set; }

    public ushort AddressId { get; set; }

    public DateTime LastUpdate { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual Staff ManagerStaff { get; set; }

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}